version: "3"

tasks:
  generate:
    task: generate
    desc: Generate Go code from protobuf
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/

# ./Taskfile.yaml
# See: https://taskfile.dev/api/
#
